name: Tests

on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout (copy) gh-pages repository to GitHub runner
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Allure
        run: |
          sudo apt-get update && \
          sudo apt-get install -y openjdk-11-jre curl tar && \
          curl -o allure-2.13.8.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.tgz && \
          tar -zxvf allure-2.13.8.tgz -C /opt/ && \
          sudo ln -s /opt/allure-2.13.8/bin/allure /usr/bin/allure && \
          rm allure-2.13.8.tgz

      - name: Run tests
        run: |
          pytest --alluredir=allure-results

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.TOKEN_CI }}
          branch: gh-pages
          folder: allure-report
          clean: true